---
title: "Segregación socioespacial y políticas de vivienda en América Latina y Chile"
bibliography: bibliografia.bib
---
<div class=text-justify>
# Patrón de segregación en América Latina

Según lo investigado en [@lopez2018segregacion] a partir de los 80's el suelo como mercancía cobra aún más valor y, en el contexto de América Latina, el estado tiene aún un rol regulador, pero que interviene con mayor fuerza en el mercado inmobiliario. Es en esta época donde se acercan los barrios marginales cerca de urbanizaciones de lujo, no significando que se dé mezcla social por haberse acortado la distancia entre las clases sociales. Las élites habitan conjuntos residenciales cerrados, con seguridad privada que les permite diferenciarse de los demás. Esta exclusividad posee principalmente servicios y equipamientos privados que los otros (población pobre) no cuentan.

Una forma de segregación que provee el mercado inmobiliario es la promoción de la construcción de conjuntos cerrados que pasan a estar juntos por la concentración de capital y por la liberalización de mercados de suelo. La otra forma de segregación es através de las fronteras donde la vivienda segregada es aquella que no posee capital necesario para crear dichos espacios privilegiados, donde estos son población estigmatizada que a la cual se le tiene miedo y se le trazan dichas fronteras.

De acuerdo a lo anterior se generan 2 tipos de injusticias: la primera es la **mala redistribución** de las estructuras económicas que no permiten que la población no se separe según nivel socioeconómico y la segunda es el **reconocimiento fallido o desigualdad de estatus** el cual se da cuando los grupos socioeconómicos más bajos son excluidos a las zonas con menores servicios y equipamiento de baja calidad. No legitimándose su cultura y a la vez estigmatizándola.

# Pauperización de la vivienda social

Respecto las razones técnicas de por qué la vivienda social en AL quedó alejada del centro y se acercó a la periferia se encuentran 3 fundamentales: La **primera** tiene que ver con que los terrenos a adquirir son más baratos. La **segunda** es que dichos terrenos son más amplios y soportan construcciones a grandes escalas. Y por último, la **tercera** es que existe menos competencia de las licitaciones con una *regulación del suelo más débil*. Consecuencia de aquello encontramos además deterioro en la accesibilidad al transporte, largas jornadas de desplazamiento y obviamente un equipamiento urbano inexistente o de mala calidad. A ello se le suma un impacto negativo en los ahorros e ingresos de estos hogares y una pérdida en las redes de apoyo [@alvarez2019hacia].

En el caso chileno, a 2006 se reconocen logros como el fin de las ocupaciones ilegales, la dotación de servicios básicos a casi toda la población y la reducción del déficit habitacional con focalización hacia la población más pobre. A la vez se puede observar aumento en la segregación socioespacial y mala calidad de la vivienda social de construcción masiva que tenía el estado apoyando al sector privado. Es aquí donde a la vez que se dio paso a la segregación socioespacial más profunda, también se dio paso a preguntarse po la segregación institucional puesto que las residencias no solo influyen en la calidad de vida de las personas por sí mismas, sino que también la ubicación residencial fue acompañada de desigualdades como el sistema de impuestos territoriales y la municipalización de la salud y la educación. *Así no solo se aisló la vivienda a la periferia de la residencia sino que también se acompañó de la mala calidad de los barrios en donde se localizaron dichos proyectos* [@ruiz2019mezcla].


# El fallo de las políticas de mezcla social en Chile

El concepto de mezcla social ha sido usado para referirse a la integración, a las comunidades de ingresos diversos y a la desconcentración de la pobreza. También se refiere a la variedad social es un lugar geográfico de cualquier índole social.

La mezcla social gira en torno 5 conceptos clave. La primera es *la hipótesis del contacto interpersonal* mencionado anteriormente en los mecanismos de la segregación socioespacial como el efecto par, que tiene como fin reducir el prejuicio entre distintos grupos sociales. El segundo concepto clave se refiere a las *redes sociales* como capital social. Este enfatiza en que las clases medias son importantes para los espacios centrales de la ciudad, puesto que la mezcla social facilitaría el desarrollo de lazos débiles entre las personas de bajos ingresos para acceder a redes de empleo. El tercer concepto es el *control social* que supone que la presencia de habitantes de altos ingresos regularía las normas de comportamiento dando un mayor orden y seguridad. El cuarto concepto postula los *modelos de rol* donde la presencia de vecinos de alto estatus lleva la adopción de comportamientos socialmente aceptables. Finalmente se habla de la *geografía de la oportunidad* donde bajo los supuestos de libre mercado, un suelo debiese atraer bienes y servicios de mayor calidad que influencia las perspectivas de los habitantes de dicho sector [@ruiz2019mezcla].

Se pueden apreciar dos etapas de la política habitacional que tuvo entre sus objetivos la mezcla social de la población. La primera se dio a partir de los *Proyectos de Integración Social (PIS)* diseñados y aplicados en el primer mandato de Michelle Bachelet que entendió esta necesidad como mejorar la calidad de las viviendas y barrios existentes (Programa Quiero Mi Barrio, Protección al Patrimonio Familiar y Modificaciones a los reglamentos del Fondo Solidario de Vivienda), lograr ,mejor localización  mediante subsidio al incentivo de compra de viviendas usadas (Programa Movilidad y Proyecto de Ley de Suelo e Integración Social), aprovechando el suelo existente que apunta a la flexibilización de los cambios de uso de suelo para instalar viviendas más la gestión de suelos públicos para la vivienda, y por último los programas de promueven la mezcla de grupos sociales con limitadas exigencias de localización (Proyecto de Desarrollo Urbano Condicionado, Proyecto de Integragación Social) [@ruiz2019mezcla].

La segunda etapa proviene del primer mandato de Sebastián Piñera con la Política Nacional de Desarrollo Urbano que propone dentro de sus ejes principales la integración social donde se diseñan los Proyctos de Reactivación económica e Integración Social (PREIS) y los Proyectos de Integración Social y Territorial (PIST).

La síntesis de estas dos etapas de las políticas no es nada alentador. La hipótesis del contacto no funcionó. Siguen existiendo límites entre los habitantes del conjunto manifestados en conflictos, malestar y baja participación que se categorizan bajo la situación socioeconómica y de acuerdo a la modalidad de adquisición de la vivienda.

No se logran los lazos débiles propuestos en las redes sociales dado que la diferencia socioeconómica de los habitantes es baja y no se genera capital social. Respecto al control social está presenta en los nuevos residentes mediante su proceso de selección. Se escogen a familias vulnerables de acuerdo a su estabilidad laboral y los antecedentes penales. Termina funcionando mediante la exclusión social. Los modelos de rol no se observan. No existe un grupo que dirija a la comunidad respecto al comportamiento (para el caso de los PIS). Y en el caso de los PREIS, los vecinos solo valoran la tenencia de un trabajo (independiente del ingreso) y no el nivel socioeconómico de los vecinos. Por último, dentro de las geografías de la oportunidad se consideró la inclusión de un colegio particular subvencionado (pagado y orientado a los sectores medios), lo cual representó una ventaja comparativa de mercado [@ruiz2019mezcla].

</div>

# Referencias

