---
title: "Conceptualización de la segregación socioespacial"
bibliography: bibliografia.bib
---
<div class=text-justify>
# ¿Qué es la segregación socioespacial (SSE)?

Puede definirse en términos generales como el grado de proximidad espacial o de aglomeración territorial de los hogares pertenecientes a un mismo grupo social. Ya sea que éste se defina en términos étnicos, etarios de preferencias religiosas o socioeconómicas entre otras posibilidades. Se manifiesta en forma de proximidad física entre los espacios residenciales de los diferentes grupos sociales, homogeneidad social de las gistintas subdivisiones territoriales en que se puede estructurar una ciudad o la concentración de grupos grupos sociales en zonas específicas de una ciudad [@rodriguez2004].

# ¿Por qué nos interesa estudiar la SSE?

Si se observan las consecuencias empíricas de estas agrupaciones, lo que prevalece son consecuencias negativas de este fenómeno urbano. En dichos sectores se puede encontrar rendimiento escolar, desempleo, embarazo adolescente, exclusión y discriminación, deteriore urbanístico-habitacional, desprotección social, delincuencia y drogadicción.

Esta actúa como un mecanismo social de reproducción de las desigualdades, de las cuales ella misma es una manifestación. Se expone que es esta la descripción de cómo se “aislan pobres”  quienes en el contexto cotidiano de pobreza solo se vinculan con pares pobres. Estos estrechan sus horizontes de posibilidades, contactos y posibilidades de exposición a ciertos códigos, mensajes y conductas funcionales a una movilidad social ascendente que además se agrava por la reducción de los ámbitos de interacción de los diferentes grupos socioeconómicos, siendo el caso de la segmentación educativa uno de los más sobresalientes. Se suma a esto que la dicho fenómeno debilita la vida comunitaria y la capacidad de acción colectiva [@rodriguez2004].

Ahora bien, existe otro tipo de efecto relativamente nuevo de la segregación que hacen que los grupos populares sean aún más pobres. En Chile, antes de la década de los 2000’s, la segregación no tenía efectos en la desintegración social que se muestra actualmente. Hoy se estarían dando fenómenos de "guetización” de los barrios populares que no existían antes o eran mucho excepcionales. Dicha "guetización”tiene otros niveles de "malignidad" que no se obervaban antes [@PUC0507].

# Mecanismo de reproducción de la SSE

El primer mecanismo se relaciona con <em>el proceso de difusión de comportamientos entre un individuo y otro, como un contagio y legitimación de comportamientos disfuncionales<em> (inactividad, deserción escolar, embarazo adolescente) conocido como <b>efecto par</b> o <b>efecto de pares</b> que se asocia a la situación de concentración espacial de pobreza, la que tiende a aumentar la probabilidad de que una persona que vive constantemente expuesta a estas condiciones, caiga en el mismo patrón recurrente.

El segundo mecanismo habla del <em>proceso de socialización colectiva</em>, donde los adultos de la comunidad actúan como modelos para los miembros más jóvenes. Lo anterior se puede categorizar por 2 clases. Cuando hay segregación de clase social alta, los adultos transfieren valores que apuntan al proceso de éxito que han tenido. En la clase social contraria, se apunta a un modelo donde no ha habido inserción laboral.

Por último, el tercer mecanismo es la <em>sociabilización institucional</em>. Es aquí donde los adultos que pertenecen a las institucionen poseen poder de juicio respecto al individuo que se adentra en dicho lugar (profesores, autoridades locales, etc.). Los adultos en estas instituciones usan criterios de funcionalidad donde interpretan atributos culturales y el potencial de los grupos sociales. Se puede resumir en la siguiente frase:


<em>"Niños pobres en áreas segregadas serán considerados disfuncionales para la educación universitaria y serán por lo tanto socializados como tales; mientras que niños en barrios mixtos o integrados serán presionados pues las oportunidades disponibles merecen el esfuerzo"</em>[@SSE1]. 

</div>

# Referencias